
#ifndef CONFIG_H
#define CONFIG_H

const char* WIFI_SSID = "iot2";
password ;

CHAR* MOTT_BROKER = "13.233.232.181";
INT MQTT_PORT = 1883;
CHAR* MQTT_CLIENT_ID  = "IOTNODE-01";

CHAR* MQTT_USERNAME = "DESD";
CHAR* MQTT_PASSWORD = "DESD123";


C* MQTT_TOPIC_PUBLISH = "CDAC/DIOT/TELEMETRY"
	MQTT_TOPIC_SUBSCRIBE = "CDAC/DIOT/LED/CONTROL"

const uint8_t NEW_MAC_ADDRESS[] = {0XDC, 0x1b, 0x64, 0x5e, 0xbf};

#ENDIF
